# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '树模型.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

from TestUI.GUI.view.Snmodule import SerialNumberModule
from TestUI.GUI.view.Statistics import StatisticsBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")

        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")

        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")


        h1 = QtWidgets.QHBoxLayout()
        self.lb_staticon = QtWidgets.QLabel()
        self.lb_staticon.setFont(QtGui.QFont("Timers", 40))
        self.lb_staticon.setStyleSheet("color: rgb(0, 0, 255);")
        h1.addWidget(self.lb_staticon)
        h1.setContentsMargins(20,0,0,0)

        h2 = QtWidgets.QHBoxLayout()
        self.lb_vs = QtWidgets.QLabel()
        self.lb_vs.setText("Version:")
        self.lb_vs.setFont(QtGui.QFont("Timers", 14))

        self.lb_version = QtWidgets.QLabel()
        lb_font = QtGui.QFont("Timers", 14)
        lb_font.setBold(True)
        self.lb_version.setFont(lb_font)

        self.lb_icon = QtWidgets.QLabel()

        #self.lb_icon.setPixmap(QtGui.QPixmap("PRMLOGO.png"))

        self.image = QtGui.QImage()
        if self.image.load("PRMLOGO.png"):

            pixmap = QtGui.QPixmap.fromImage(self.image)
            picSize = QtCore.QSize(200, 60)
            scaledPixmap = pixmap.scaled(picSize)
            self.lb_icon.setScaledContents(True)
            self.lb_icon.setPixmap(scaledPixmap)


        spacerItem = QtWidgets.QSpacerItem(0,0,QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        h2.addItem(spacerItem)
        h2.addWidget(self.lb_vs)
        h2.addWidget(self.lb_version)
        

        h2.setSpacing(0)
        h2.setContentsMargins(0,30,0,0)

        st_space = QtWidgets.QSpacerItem(0,0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        h3 = QtWidgets.QHBoxLayout()

        h3.addItem(st_space)

        h3.addWidget(self.lb_icon, 1)
        h3.setContentsMargins(0,30,0,0)
        h3.setSpacing(0)

        self.horizontalLayout_15.addLayout(h1,1)
        self.horizontalLayout_15.addLayout(h2,2)
        self.horizontalLayout_15.addLayout(h3,1)


        self.fm = QtWidgets.QFrame()
        self.fm.setLayout(self.horizontalLayout_15)

        self.horizontalLayout_16.addWidget(self.fm)

        self.verticalLayout_4.addLayout(self.horizontalLayout_16,1)
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")

        self.groupBox = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)

        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.treeView = QtWidgets.QTreeView()

        font = QtGui.QFont()
        font.setFamily(".SF NS Text")
        font.setPointSize(16)
        font.setKerning(True)
        self.treeView.setFont(font)
        self.treeView.setFrameShape(QtWidgets.QFrame.Box)
        self.treeView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.treeView.setMidLineWidth(0)
        self.treeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.treeView.setAlternatingRowColors(False)
        self.treeView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.treeView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.treeView.setAutoExpandDelay(0)
        self.treeView.setUniformRowHeights(False)
        self.treeView.setAllColumnsShowFocus(True)
        self.treeView.setObjectName("treeView")
        self.treeView.header().setCascadingSectionResizes(False)
        self.treeView.header().setHighlightSections(True)
        self.treeView.header().setSortIndicatorShown(False)
        self.treeView.header().setStretchLastSection(True)

        self.ftreeView = QtWidgets.QTreeView()
        self.ftreeView.setFont(font)
        self.ftreeView.setFrameShape(QtWidgets.QFrame.Box)
        self.ftreeView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ftreeView.setMidLineWidth(0)
        self.ftreeView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.ftreeView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.ftreeView.setAlternatingRowColors(False)
        self.ftreeView.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.ftreeView.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ftreeView.setAutoExpandDelay(0)
        self.ftreeView.setUniformRowHeights(False)
        self.ftreeView.setAllColumnsShowFocus(True)
        self.ftreeView.setObjectName("treeView")
        self.ftreeView.header().setCascadingSectionResizes(False)
        self.ftreeView.header().setHighlightSections(True)
        self.ftreeView.header().setSortIndicatorShown(False)
        self.ftreeView.header().setStretchLastSection(True)
        #self.horizontalLayout_12.addWidget(self.treeView)
        self.tab = QtWidgets.QTabWidget()
        self.tab.addTab(self.treeView,"Totals")
        self.tab.addTab(self.ftreeView,"FailSummary")

        self.horizontalLayout.addWidget(self.tab)

        self.frame_5 = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.frame_3 = QtWidgets.QFrame(self.frame_5)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.setStyleSheet("background-color: rgb(230, 230, 230);")


        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.start = QtWidgets.QPushButton(self.frame_3)

        self.start.setText("Start")
        self.start.setObjectName("start")
        self.start.setMinimumHeight(40)
        self.start.setFont(QtGui.QFont("Timers", 28,QtGui.QFont.Bold))
        #self.start.setDisabled(False)
        self.horizontalLayout_11.addWidget(self.start,1)

        btsp = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_11.addItem(btsp)

        self.abort = QtWidgets.QPushButton(self.frame_3)
        self.abort.setText("Abort")
        self.abort.setObjectName("abort")
        self.abort.setFont(QtGui.QFont("Timers", 28,QtGui.QFont.Bold))
        self.horizontalLayout_11.addWidget(self.abort,1)
        self.abort.setMinimumHeight(40)
        self.abort.setDisabled(True)

        self.horizontalLayout_11.setContentsMargins(20,0,20,40)
        #self.horizontalLayout_11.setSpacing(40)

        self.btframe = QtWidgets.QFrame()
        self.btframe.setLayout(self.horizontalLayout_11)
        self.sn = SerialNumberModule(uut=4)
        self.pst = StatisticsBox()


        snFrame = QtWidgets.QFrame()
        self.scanSn = QtWidgets.QLineEdit()
        scanName = QtWidgets.QLabel("SN:")
        snlayout = QtWidgets.QHBoxLayout()
        snlayout.addWidget(scanName)
        snlayout.addWidget(self.scanSn)
        snlayout.setContentsMargins(20,0,20,0)
        snFrame.setLayout(snlayout)

        self.vtlayout = QtWidgets.QVBoxLayout()
        self.vtlayout.addWidget(self.sn)
        self.vtlayout.addWidget(snFrame)
        self.vtlayout.addWidget(self.pst)
        self.vtlayout.addWidget(self.btframe)
        self.vtlayout.setSpacing(50)

        self.verticalLayout_5.addLayout(self.vtlayout)
        sp = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(sp)
        #self.verticalLayout_5.addLayout(self.verticalLayout_2)

        self.verticalLayout_3.addWidget(self.frame_3)
        self.verticalLayout_3.setStretch(1, 3)
        self.verticalLayout_3.setStretch(2, 4)
        self.splayout = QtWidgets.QVBoxLayout()
        self.splayout.setSpacing(0)
        self.splayout.setContentsMargins(0,0,0,0)
        self.splayout.addWidget(self.splitter)
        self.verticalLayout_4.addLayout(self.splayout,5)


        #self.verticalLayout_4.addWidget(self.splitter)


        # self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        # self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        # self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        # self.frame_6.setObjectName("frame_6")
        #
        # self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_6)
        # self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        # self.horizontalLayout_14.setSpacing(0)
        # self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        # self.label = QtWidgets.QLabel(self.frame_6)
        # self.label.setMinimumSize(QtCore.QSize(1000, 50))
        # self.label.setMaximumSize(QtCore.QSize(1600, 50))
        # self.label.setText("")
        # self.label.setPixmap(QtGui.QPixmap(":/picture/logo.png"))
        # self.label.setScaledContents(True)
        # self.label.setWordWrap(False)
        # self.label.setObjectName("label")
        # self.horizontalLayout_14.addWidget(self.label)
        # self.verticalLayout_4.addWidget(self.frame_6)
        # self.verticalLayout_4.setStretch(0, 1)
        # self.verticalLayout_4.setStretch(1, 6)
        # self.verticalLayout_4.setStretch(2, 1)
        # self.splitter.raise_()
        # self.frame_6.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)

        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1251, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuIdentity = QtWidgets.QMenu(self.menuSettings)
        self.menuIdentity.setObjectName("menuIdentity")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuPDCA = QtWidgets.QMenu(self.menuView)
        self.menuPDCA.setObjectName("menuPDCA")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSet_Password = QtWidgets.QAction(MainWindow)
        self.actionSet_Password.setObjectName("actionSet_Password")
        self.actionSupervisor = QtWidgets.QAction(MainWindow)
        self.actionSupervisor.setObjectName("actionSupervisor")
        self.actionOperator = QtWidgets.QAction(MainWindow)
        self.actionOperator.setObjectName("actionOperator")
        self.actionsupervisor = QtWidgets.QAction(MainWindow)
        self.actionsupervisor.setObjectName("actionsupervisor")
        self.actionScriptEditorTool = QtWidgets.QAction(MainWindow)
        self.actionScriptEditorTool.setObjectName("actionScriptEditorTool")
        self.actionLoopTest = QtWidgets.QAction(MainWindow)
        self.actionLoopTest.setObjectName("actionLoopTest")
        self.actionPdcaopen = QtWidgets.QAction(MainWindow)
        self.actionPdcaopen.setObjectName("actionPdcaopen")
        self.actionPdcaclose = QtWidgets.QAction(MainWindow)
        self.actionPdcaclose.setObjectName("actionPdcaclose")
        self.actionMainWindow = QtWidgets.QAction(MainWindow)
        self.actionMainWindow.setObjectName("actionMainWindow")
        self.actionTestengine1 = QtWidgets.QAction(MainWindow)
        self.actionTestengine1.setObjectName("actionTestengine1")
        self.actionTestengine2 = QtWidgets.QAction(MainWindow)
        self.actionTestengine2.setObjectName("actionTestengine2")
        self.actionTestengine3 = QtWidgets.QAction(MainWindow)
        self.actionTestengine3.setObjectName("actionTestengine3")
        self.actionTestengine4 = QtWidgets.QAction(MainWindow)
        self.actionTestengine4.setObjectName("actionTestengine4")
        self.actionStatemachine = QtWidgets.QAction(MainWindow)
        self.actionStatemachine.setObjectName("actionStatemachine")
        self.actionClean = QtWidgets.QAction(MainWindow)
        self.actionClean.setObjectName("actionClean")
        self.menuFile.addAction(self.actionOpen)
        self.menuIdentity.addAction(self.actionOperator)
        self.menuIdentity.addAction(self.actionsupervisor)
        self.menuSettings.addAction(self.actionSet_Password)
        self.menuSettings.addAction(self.menuIdentity.menuAction())
        self.menuSettings.addAction(self.actionClean)
        self.menuPDCA.addAction(self.actionPdcaopen)
        self.menuPDCA.addAction(self.actionPdcaclose)
        self.menuView.addAction(self.actionScriptEditorTool)
        self.menuView.addAction(self.actionLoopTest)
        self.menuView.addAction(self.menuPDCA.menuAction())
        self.menuView.addAction(self.actionMainWindow)
        self.menuView.addAction(self.actionTestengine1)
        self.menuView.addAction(self.actionTestengine2)
        self.menuView.addAction(self.actionTestengine3)
        self.menuView.addAction(self.actionTestengine4)
        self.menuView.addAction(self.actionStatemachine)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.splitter.setSizes([1300,500])

        # display F/F Sate

        self.retranslateUi(MainWindow)
        #self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        # self.label_31.setText(_translate("MainWindow", "Sequence"))
        # self.label_38.setText(_translate("MainWindow", "Engine"))
        # self.label_32.setText(_translate("MainWindow", "Logger"))
        # self.label_13.setText(_translate("MainWindow", "Elapsed Time："))
        # self.uut1time.setText(_translate("MainWindow", "00-00-00-00"))
        # self.label_15.setText(_translate("MainWindow", "Elapsed Time："))
        # self.uut2time.setText(_translate("MainWindow", "00-00-00-00"))
        # self.label_18.setText(_translate("MainWindow", "Elapsed Time："))
        # self.uut3time.setText(_translate("MainWindow", "00-00-00-00"))
        # self.label_20.setText(_translate("MainWindow", "Elapsed Time："))
        # self.uut4time.setText(_translate("MainWindow", "00-00-00-00"))
        # self.PDCA.setText(_translate("MainWindow", "NOPDCA"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuIdentity.setTitle(_translate("MainWindow", "Identity"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuPDCA.setTitle(_translate("MainWindow", "PDCA"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSet_Password.setText(_translate("MainWindow", "Set Password"))
        self.actionSupervisor.setText(_translate("MainWindow", "Supervisor"))
        self.actionOperator.setText(_translate("MainWindow", "Operator"))
        self.actionsupervisor.setText(_translate("MainWindow", "Supervisor"))
        self.actionScriptEditorTool.setText(_translate("MainWindow", "ScriptEditor"))
        self.actionLoopTest.setText(_translate("MainWindow", "LoopTest"))
        self.actionPdcaopen.setText(_translate("MainWindow", "Open"))
        self.actionPdcaclose.setText(_translate("MainWindow", "Close"))
        self.actionMainWindow.setText(_translate("MainWindow", "mainWindow"))
        self.actionTestengine1.setText(_translate("MainWindow", "Testengine1"))
        self.actionTestengine2.setText(_translate("MainWindow", "Testengine2"))
        self.actionTestengine3.setText(_translate("MainWindow", "Testengine3"))
        self.actionTestengine4.setText(_translate("MainWindow", "Testengine4"))
        self.actionStatemachine.setText(_translate("MainWindow", "Statemachine"))
        self.actionClean.setText(_translate("MainWindow", "Clean"))

        # self.lbl_P_1.setText(_translate("MainWindow", "P:"))
        # self.lbl_pass_1.setText(_translate("MainWindow", "0"))
        # self.lbl_F_1.setText(_translate("MainWindow", "F:"))
        # self.lbl_fail_1.setText(_translate("MainWindow", "0"))
        # self.lbl_T_1.setText(_translate("MainWindow", "Total:"))
        # self.lbl_total_1.setText(_translate("MainWindow", "0"))
        # self.lbl_R_1.setText(_translate("MainWindow", "Rate:"))
        # self.lbl_rate_1.setText(_translate("MainWindow", "0"))
        # self.lbl_U_1.setText(_translate("MainWindow", "%"))
        #
        # self.lbl_P_2.setText(_translate("MainWindow", "P:"))
        # self.lbl_pass_2.setText(_translate("MainWindow", "0"))
        # self.lbl_F_2.setText(_translate("MainWindow", "F:"))
        # self.lbl_fail_2.setText(_translate("MainWindow", "0"))
        # self.lbl_T_2.setText(_translate("MainWindow", "Total:"))
        # self.lbl_total_2.setText(_translate("MainWindow", "0"))
        # self.lbl_R_2.setText(_translate("MainWindow", "Rate:"))
        # self.lbl_rate_2.setText(_translate("MainWindow", "0"))
        # self.lbl_U_2.setText(_translate("MainWindow", "%"))
        self.start.setToolTip(_translate("MainWindow", "<html><head/><body><p> Press F2 To Start</p></body></html>"))


import appqrc_rc
